### ISSUE TITLE
Bug: can't disable battery, weather and network

### ISSUE THREAD

**Issue by ankush** [danerwilliams/tmux-dracula#137]
### To Reproduce
 
Add this to your `.tmux.conf`:

```
set -g @dracula-show-battery false
set -g @dracula-show-weather false
set -g @dracula-show-network false
```

### Expected behavior
Battery, weather and network are not shown. 

### System
 - OS: Mac OS Big Sur
- Tmux Version: 3.2A

### Additional info

This used to work before, Git bisect suggests 4abfcf279949b6c301d3c853a204fe01dbe8c587 broke it. (maybe intentional?)  I'll try to send a fix if I find a root cause.

**Comment by ankush** [comment]
nvm. This was breaking a change from v2.

Much simpler way to specify plugins now.

e.g. `set -g @dracula-plugins "time"`

**Comment by CavalcanteLucas** [comment]
Thank you for your answer.. It really helped me.

However, how to use multiple plugins?

For instance, if i try to add the lines

```
set -g @dracula-plugins "ram-usage"
set -g @dracula-plugins "cpu-usage"
```

The last plugin overwrites the first one.

**Comment by RicardoRien** [comment]
Ok, but how can I hide battery, weather and network?

**Comment by RicardoRien** [comment]
So, we hide all those things with:
`set -g @dracula-plugins ""`

**Comment by MrCyberBong** [comment]
@RicardoRien Is this confirmed? It doesn't work in my case. I want to hide everything on the right but the only option which works is the show-location false option. Setting show-battery etc. to false doesn't hide those infos

**Comment by MrCyberBong** [comment]
nvm got it working by putting a space between the quotation marks. So `set -g @dracula-plugins " "` hides all infos

**Comment by abu-matterize** [comment]
> Thank you for your answer!
> 
> Just a minor add:
> 
> If you want to use multiple plugins, you can use it like:
> 
> ```
> set -g @dracula-plugins "ram-usage cpu-usage time"
> ```

How to make it show the hostname and if the session is into ssh, the remote hostname?
